name: Node CI (beta)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install dependencies of web3.js
      working-directory: ./web3.js
      run: npm ci
    - name: Build web3.js
      working-directory: ./web3.js
      run: npm run build
    - name: Install dependencies of web3.js-browser
      run: yarn install --frozen-lockfile
    - name: Build web3.js-browser
      run: |
        npm run build
        npm run build:prod
      env:
        CI: true
    - name: Upload built files
      uses: actions/upload-artifact@v1
      with:
        name: web3.js-browser-dist
        path: dist
